const VNODE_TYPES = {
  // html 标签
  ELEMENT_HTML: 1,
  // SVG 标签
  ELEMENT_SVG: 1 << 1,

  // 普通有状态组件
  COMPONENT_STATEFUL_NORMAL: 1 << 2,
  // 需要被keepAlive的有状态组件
  COMPONENT_STATEFUL_SHOULD_KEEP_ALIVE: 1 << 3,
  // 已经被keepAlive的有状态组件
  COMPONENT_STATEFUL_KEPT_ALIVE: 1 << 4,
  // 函数式组件
  COMPONENT_FUNCTIONAL: 1 << 5,

  // 纯文本
  TEXT: 1 << 6,
  // 注释
  COMMENT: 1 << 9,
  // Fragment
  FRAGMENT: 1 << 7,
  // Portal
  PORTAL: 1 << 8
}

VNODE_TYPES.ELEMENT = VNODE_TYPES.ELEMENT_HTML | VNODE_TYPES.ELEMENT_SVG

VNODE_TYPES.COMPONENT_STATEFUL =
  VNODE_TYPES.COMPONENT_STATEFUL_NORMAL |
  VNODE_TYPES.COMPONENT_STATEFUL_SHOULD_KEEP_ALIVE |
  VNODE_TYPES.COMPONENT_STATEFUL_KEPT_ALIVE

VNODE_TYPES.COMPONENT = VNODE_TYPES.COMPONENT_STATEFUL | VNODE_TYPES.COMPONENT_FUNCTIONAL

VNODE_TYPES.TEXT_COMMENT = VNODE_TYPES.TEXT | VNODE_TYPES.COMMENT


const CHILD_TYPES = {
  // 未知的 children 类型
  UNKNOWN_CHILDREN: 0,
  // 没有 children
  NO_CHILDREN: 1,
  // children 是单个 VNode
  SINGLE_VNODE: 1 << 1,

  // children 是多个拥有 key 的 VNode
  KEYED_VNODES: 1 << 2,
  // children 是多个没有 key 的 VNode
  NONE_KEYED_VNODES: 1 << 3
}

CHILD_TYPES.MULTIPLE_VNODES = CHILD_TYPES.KEYED_VNODES | CHILD_TYPES.NONE_KEYED_VNODES